### ISSUE TITLE
GPTQ example: load_dataset("wikitext") fails under huggingface_hub 1.3+

### ISSUE THREAD

**Issue by hseok-oh** [Samsung/TICO#814]
### Summary

`tico/quantization/wrapq/examples/quantize_full_qmodel_with_gptq.py` is written for **transformers 5.x**, but it loads the Wikitext calibration/eval dataset using the **legacy, namespace-less** dataset id. That id is rejected by the `huggingface_hub` version that transformers 5.x requires, so the example crashes before any quantization work happens.

```python
# tico/quantization/wrapq/examples/quantize_full_qmodel_with_gptq.py
DATASET_NAME = "wikitext"            # L106
DATASET_CONFIG = "wikitext-2-raw-v1" # L107
```

### Error

```
huggingface_hub.errors.HfUriError: Invalid HF URI 'hf://datasets/wikitext@ae70e4dc86c9b3b167b87a6a3c9a4ea32f0307f0/.huggingface.yaml'. Repository id must be 'namespace/name', got 'wikitext'.
```

<details><summary>Full traceback</summary>

```
Traceback (most recent call last):
  File ".../quantize_full_qmodel_with_gptq.py", line 1447, in <module>
    main()
  File ".../quantize_full_qmodel_with_gptq.py", line 1431, in main
    dataset_test = load_eval_dataset(args)
  File ".../quantize_full_qmodel_with_gptq.py", line 1233, in load_eval_dataset
    return load_dataset(
  File ".../datasets/load.py", line 1698, in load_dataset
    builder_instance = load_dataset_builder(
  File ".../datasets/load.py", line 1325, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File ".../datasets/load.py", line 1217, in dataset_module_factory
    raise e1 from None
  File ".../datasets/load.py", line 1192, in dataset_module_factory
    ).get_module()
  File ".../datasets/load.py", line 608, in get_module
    standalone_yaml_path = cached_path(
  File ".../datasets/utils/file_utils.py", line 180, in cached_path
    ).resolve_path(url_or_filename)
  File ".../huggingface_hub/hf_file_system.py", line 305, in resolve_path
    parsed = parse_hf_uri(f"{constants.HF_PROTOCOL}{path}")
  File ".../huggingface_hub/utils/_hf_uris.py", line 319, in parse_hf_uri
    return _parse_repo_body(location, type_, raw=raw)
  File ".../huggingface_hub/utils/_hf_uris.py", line 617, in _parse_repo_body
    raise HfUriError(uri=raw, msg=f"Repository id must be 'namespace/name', got '{repo_id}'.")
huggingface_hub.errors.HfUriError: Invalid HF URI 'hf://datasets/wikitext@ae70e4dc86c9b3b167b87a6a3c9a4ea32f0307f0/.huggingface.yaml'. Repository id must be 'namespace/name', got 'wikitext'.
```

</details>

### Root cause / version inconsistency

The script assumes transformers **5.x**:

- `AutoModelForCausalLM.from_pretrained(..., dtype=dtype, ...)` (L1167) uses the 5.x `dtype=` kwarg. On 4.x this raises `LlamaForCausalLM.__init__() got an unexpected keyword argument 'dtype'` (the kwarg was `torch_dtype`).
- `test/requirements.txt` pins `transformers==5.9.0`.

But transformers 5.x depends on `huggingface_hub>=1.3.0,<2.0`, and `huggingface_hub` 1.3+ enforces the `namespace/name` form in its `hf://` URI parser (`parse_hf_uri`). The bare canonical id `"wikitext"` predates that requirement, so it is incompatible with the very hub version the script requires. There is no version-adaptive guard in the script.

This also makes the dependency set unsatisfiable if the bare id is kept: any `datasets` new enough to work with `huggingface_hub>=1.3` rejects `"wikitext"`, while any `datasets` old enough to accept it requires `huggingface_hub<1.0` — which conflicts with `transformers 5.x`:

```
transformers 5.0.0 depends on huggingface-hub<2.0 and >=1.3.0
datasets 2.14.0   depends on huggingface-hub<1.0.0 and >=0.14.0
```

### Suggested fix

Use the namespaced canonical mirror. It is the same dataset — same `wikitext-2-raw-v1` config, same `text` string column, same `train`/`validation`/`test` splits (verified via the HF datasets-server) — and HF redirects `wikitext` → `Salesforce/wikitext` server-side. Only the client-side URI validation rejects the bare form.

```python
DATASET_NAME = "Salesforce/wikitext"
```

Minor note: `DATASET_NAME` is also passed to `get_sensitivities_info_name()` to build a filename, where `/` is not sanitized (unlike `model.config.name_or_path.replace("/", "_")`). But the call site uses `pathlib.Path(...).name`, so the only effect is a slightly different — still valid — filename, and only when `--save sensitivity` with `--gptq_mse smse*` is used. No functional impact on quantization.

### Reproduction

```bash
python tico/quantization/wrapq/examples/quantize_full_qmodel_with_gptq.py \
  --model Maykeye/TinyLLama-v0 --device cpu \
  --output_dir /tmp/out --save circle_per_layer --max_seq_len 64 \
  --linear_weight_bits 4 --embedding_weight_bits 4 --lm_head_weight_bits 4 \
  --decode_calibration_steps 0
```

Fails at `load_eval_dataset` → `load_dataset("wikitext", "wikitext-2-raw-v1", ...)`.

### Environment

- transformers 5.0.0 / 5.9.0, huggingface_hub 1.3+
- File at commit 79a9bd7 (`main`): `tico/quantization/wrapq/examples/quantize_full_qmodel_with_gptq.py` L106

**Comment by mhs4670go** [comment]
@hseok-oh I've fix the issue. Could you check the error again?
